### ISSUE TITLE
I don't know what your code is for, but it has several problems.

### ISSUE THREAD

**Issue by waymao** [tzx-public/lib#1]
Hi,
Glad to see you here on GitHub. 
Despite having no C experience, I read it, and found several problems.

I understand that you may want to read a line of chars from a file. However, this is not usually the good way.
The thing your function is returning is the index of a character, not the character itself. Thus, allocating memory to store the content of the characters seemed unnecessary.

And, if you use C++, you may reduce your code size dramatically. You don't really have to write like this. If you're learning C or have some specific things to do, just do it. If not, why not select an easier language?

Also, you really do not need to put the full version of BSD license in every file. Just put one in the LICENSE, and refer to this license in other files.

Anyway, I hope you will enjoy your time at GitHub.

**Comment by tzx-public** [comment]
Thanks for the issue. Maybe it's the return type of the function that made you misunderstood the purpose of this function. Anyway, I have changed the return type to "char*". 

The purpose of the function is to prompt user for the input, and store the input into a "string" (actually a pointer "char*"), regardless of the size of the chunk of memory it's initially pointing to. 

I'm aware that the library is totally unnecessary for a C++ programmer. However, since there's no such data type called "string" in C, the library (though unfinished) is quite useful for C programmers to manipulate strings in a similarly convenient way as in C++. 

There's still a lot of work to do. And I'm really looking forward to your more advice, or even pull requests!
